export const POSTS_LOADING = "POSTS_LOADING";
export const ADD_POSTS = "ADD_POSTS";
export const POSTS_FAILED = "POSTS_FAILED";
export const HIGHLIGHTS_LOADING = "HIGHLIGHTS_LOADING";
export const ADD_HIGHLIGHTS = "ADD_HIGHLIGHTS";
export const HIGHLIGHTS_FAILED = "HIGHLIGHTS_FAILED";
