export default {
  posts: [
    {
      id: 0,
      userId: 1,
      user: "Madhav",
      username: "memadcoder",
      image: "images/uthappizza.png",
      date: "Nov 16 2020",
      likes: [],
      unlikes: [],
      highlight: [],
      shares: [],
      title: "Title 1stt",
      description:
        "A unique combination of Indian Uthappam (pancake) and Italian pizza, topped with Cerignola olives, ripe vine cherry tomatoes, Vidalia onion, Guntur chillies and Buffalo Paneer.",
    },
    {
      id: 1,
      userId: 2,
      user: "Ramchandra",
      username: "ram",
      image: "images/uthappizza.png",
      date: "Mar 6 2020",
      title: "Title 2nd",
      likes: [],
      unlikes: [],
      highlight: [],
      shares: [],
      description:
        "A unique combination of Indian Uthappam (pancake) and Italian pizza, topped with Cerignola olives, ripe vine cherry tomatoes, Vidalia onion, Guntur chillies and Buffalo Paneer.",
    },
    {
      id: 2,
      userId: 1,
      user: "Madhav",
      username: "memadcoder",
      image: "images/uthappizza.png",
      date: "Jan 2 2020",
      title: "Title 3rd",
      likes: [],
      unlikes: [],
      highlight: [],
      shares: [],
      description:
        "A unique combination of Indian Uthappam (pancake) and Italian pizza, topped with Cerignola olives, ripe vine cherry tomatoes, Vidalia onion, Guntur chillies and Buffalo Paneer.",
    },
    {
      id: 3,
      userId: 3,
      user: "Sharmila",
      username: "sharmu",
      image: "images/uthappizza.png",
      date: "Dec 5 2019",
      title: "Title 4th",
      likes: [],
      unlikes: [],
      highlight: [],
      shares: [],
      description:
        "A unique combination of Indian Uthappam (pancake) and Italian pizza, topped with Cerignola olives, ripe vine cherry tomatoes, Vidalia onion, Guntur chillies and Buffalo Paneer.",
    },
  ],
};
