export default {
  posts: [
    {
      id: 0,
      userId: 1,
      user: "Madhav",
      username: "memadcoder",
      image: "images/uthappizza.png",
      date: "Nov 16 2020",
      likes: [{ userId: 2 }],
      unlikes: [{ userId: 2 }],
      highlight: [{ userId: 1 }, { userId: 2 }],
      shares: [{ userId: 2 }],
      title: "Title 1stt",
      description:
        "A unique combination of Indian Uthappam (pancake) and Italian pizza, topped with Cerignola olives, ripe vine cherry tomatoes, Vidalia onion, Guntur chillies and Buffalo Paneer.",
    },
    {
      id: 1,
      userId: 2,
      user: "Ramchandra",
      username: "ram",
      image: "images/uthappizza.png",
      date: "Mar 6 2020",
      title: "Title 2nd",
      likes: [{ userId: 1 }],
      unlikes: [{ userId: 2 }],
      highlight: [{ userId: 2 }],
      shares: [{ userId: 1 }],
      description:
        "A unique combination of Indian Uthappam (pancake) and Italian pizza, topped with Cerignola olives, ripe vine cherry tomatoes, Vidalia onion, Guntur chillies and Buffalo Paneer.",
    },
    {
      id: 3,
      userId: 1,
      user: "Madhav",
      username: "memadcoder",
      image: "images/uthappizza.png",
      date: "Jan 2 2020",
      title: "Title 3rd",
      likes: [{ userId: 3 }, { userId: 2 }, { userId: 1 }],
      unlikes: [{ userId: 3 }],
      highlight: [{ userId: 3 }],
      shares: [{ userId: 3 }],
      description:
        "A unique combination of Indian Uthappam (pancake) and Italian pizza, topped with Cerignola olives, ripe vine cherry tomatoes, Vidalia onion, Guntur chillies and Buffalo Paneer.",
    },
    {
      id: 4,
      userId: 3,
      user: "Sharmila",
      username: "sharmu",
      image: "images/uthappizza.png",
      date: "Dec 5 2019",
      title: "Title 4th",
      likes: [{ userId: 2 }, { userId: 1 }],
      unlikes: [{ userId: 2 }],
      highlight: [{ userId: 1 }, { userId: 3 }],
      shares: [{ userId: 2 }],
      description:
        "A unique combination of Indian Uthappam (pancake) and Italian pizza, topped with Cerignola olives, ripe vine cherry tomatoes, Vidalia onion, Guntur chillies and Buffalo Paneer.",
    },
  ],
  highlights: [
    {
      id: 0,
      userId: 1,
      postId: 4,
    },
    {
      id: 1,
      userId: 2,
      postId: 0,
    },
    {
      id: 2,
      userId: 2,
      postId: 1,
    },
    {
      id: 3,
      userId: 3,
      postId: 1,
    },
    {
      id: 4,
      userId: 1,
      postId: 0,
    },
  ],
};
